[build]
  publish = "public"
  functions = "functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  framework = "#static"
  port = 3000
  targetPort = 3000
  publish = "public"
  autoLaunch = true 